on:
  workflow_dispatch:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4 
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel
          pip install -U keyrings.google-artifactregistry-auth
      - name: Build package
        run: |
          python3 -m build
      - uses: 'google-github-actions/auth@v3'
        with:
          workload_identity_provider: "projects/305452601764/locations/global/workloadIdentityPools/builders/providers/github"
      - uses: pypa/gh-action-pypi-publish@v1.13.0
        with:
          repository-url: https://us-python.pkg.dev/oss-exit-gate-dev/cronk--testpypi
      # - uses: google-github-actions/setup-gcloud@v1
      # - run: |
      #     echo "test" > test.txt
      #     gcloud storage cp test.txt gs://oss-exit-gate-dev-wif-test-bucket --verbosity=debug --log-http
